// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SignatureAlgorithm.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Security source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Security.Recipes
{
    /// <summary>
    /// A signature algorithm.
    /// </summary>
#if !OBeautifulCodeSecurityRecipesProject
    [System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Security", "See package version number")]
    internal
#else
    public
#endif
    enum SignatureAlgorithm
    {
#pragma warning disable CS1591
#pragma warning disable SA1602
        None,

        Md2WithRsaEncryption,

        Md5WithRsaEncryption,

        Sha1WithRsaEncryption,

        Sha224WithRsaEncryption,

        Sha256WithRsaEncryption,

        Sha384WithRsaEncryption,

        Sha512WithRsaEncryption,

        IdRsassaPss,

        RsaSignatureWithRipeMd160,

        RsaSignatureWithRipeMd128,

        RsaSignatureWithRipeMd256,

        IdDsaWithSha1,

        DsaWithSha224,

        DsaWithSha256,

        DsaWithSha384,

        DsaWithSha512,

        EcDsaWithSha1,

        EcDsaWithSha224,

        EcDsaWithSha256,

        EcDsaWithSha384,

        EcDsaWithSha512,

        GostR3411x94WithGostR3410x94,

        GostR3411x94WithGostR3410x2001,

#pragma warning restore SA1602
#pragma warning restore CS1591
    }
}
